from pathlib import Path
p=Path('.pitch-build/build.mjs')
s=p.read_text(encoding='utf-8')
s=s.replace("const ROOT=process.cwd();", "process.env.RUNTIME_NODE_MODULES='C:/Users/lubw1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';\nconst ROOT=process.cwd();")
s=s.replace('膝盖往外打开，这一次才算有效','膝盖往外打开，指导就在动作发生时')
s=s.replace('完成一次有效动作周期，次数才增加','完成一次完整动作周期，次数随之增加')
s=s.replace('有效周期','完整周期').replace('有效次数','动作次数').replace('有效动作','完整动作')
s=s.replace('动作教练、考核记录\\n复训、答疑、批次报告','动作教练、考核记录\\n复训、答疑\\n批次报告')
s=s.replace('对应六类现场规则\\n分别输出事件与处置提示','对应六类现场规则\\n输出事件证据\\n提供处置提示')
s=s.replace('事件复核、样本管理\\n模型训练、权重管理','事件复核、样本\\n模型训练\\n权重管理')
s=s.replace('ONNX 与 PTH 权重\\n无需逐帧调用云模型','本地模型权重\\n逐帧推理在本地')
s=s.replace('机位、遮挡、不同员工\\n统计错误与复核负担','机位与遮挡变化\\n不同员工参与\\n统计错误与复核量')
s=s.replace('岗位规则、真实纠错样本、人工复核结果','经确认的岗位规则与纠错样本')
p.write_text(s,encoding='utf-8')
p=Path('deliverables/练了么-全球智能体大赛A赛道路演大纲.md')
s=p.read_text(encoding='utf-8').replace('膝盖往外打开，这一次才算有效','膝盖往外打开，指导就在动作发生时').replace('有效周期','完整周期').replace('有效动作周期','完整动作周期')
s=s.replace('| 招聘认证 |', '| 计数与纠错 | 当前计数依据阶段循环，未将全部错误码作为拒计条件 | 分别讲纠错和完整周期计数，不承诺错误动作一律不计数 |\n| 招聘认证 |')
p.write_text(s,encoding='utf-8')
